
declare -a args=(
    "-t 1 -m history -s small -G unionized"
    "-t 1 -m history -s small -G nuclide"
    "-t 1 -m history -s small -G hash"
    "-t 1 -m history -s large -G unionized"
    "-t 1 -m history -s large -G nuclide"
    "-t 1 -m history -s large -G hash"
    "-t 1 -m history -s XL -G unionized"
    "-t 1 -m history -s XL -G nuclide"
    "-t 1 -m history -s XL -G hash"
    "-t 1 -m history -s XXL -G unionized"
    "-t 1 -m history -s XXL -G nuclide"
    "-t 1 -m history -s XXL -G hash"
    "-t 1 -m event -s small -G unionized"
    "-t 1 -m event -s small -G nuclide"
    "-t 1 -m event -s small -G hash"
    "-t 1 -m event -s large -G unionized"
    "-t 1 -m event -s large -G nuclide"
    "-t 1 -m event -s large -G hash"
    "-t 1 -m event -s XL -G unionized"
    "-t 1 -m event -s XL -G nuclide"
    "-t 1 -m event -s XL -G hash"
    "-t 1 -m event -s XXL -G unionized"
    "-t 1 -m event -s XXL -G nuclide"
    "-t 1 -m event -s XXL -G hash"

    "-t 32 -m history -s small -G unionized"
    "-t 32 -m history -s small -G nuclide"
    "-t 32 -m history -s small -G hash"
    "-t 32 -m history -s large -G unionized"
    "-t 32 -m history -s large -G nuclide"
    "-t 32 -m history -s large -G hash"
    "-t 32 -m history -s XL -G unionized"
    "-t 32 -m history -s XL -G nuclide"
    "-t 32 -m history -s XL -G hash"
    "-t 32 -m history -s XXL -G unionized"
    "-t 32 -m history -s XXL -G nuclide"
    "-t 32 -m history -s XXL -G hash"
    "-t 32 -m event -s small -G unionized"
    "-t 32 -m event -s small -G nuclide"
    "-t 32 -m event -s small -G hash"
    "-t 32 -m event -s large -G unionized"
    "-t 32 -m event -s large -G nuclide"
    "-t 32 -m event -s large -G hash"
    "-t 32 -m event -s XL -G unionized"
    "-t 32 -m event -s XL -G nuclide"
    "-t 32 -m event -s XL -G hash"
    "-t 32 -m event -s XXL -G unionized"
    "-t 32 -m event -s XXL -G nuclide"
    "-t 32 -m event -s XXL -G hash"
)

